### ISSUE TITLE
Set up unit test.

### ISSUE THREAD

**Issue by dhmoon91** [dhmoon91/porobot#18]
Let's setup unit test for `rank` command. 

Requirements;
- Record sample response data from riot API request.
- check output matches against `snapshot` of data.
Create new test run command into new `.yml` that gets triggered upon new push.

**Comment by HelloFive** [comment]
Lesson learned:
- How to mock API calls (from https://changhsinlee.com/pytest-mock/)
- `Postgres does not rollback advances in a sequence even if the sequence is used in a transaction which is rolled back.` (from https://stackoverflow.com/a/12443800)
- Could not use `SAVEPOINT` or `rollback()` since change was already commited (from https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#using-savepoint)
- Could not use `pg_dump` or `pg_dumpall` to backup and restore DB since these commands to not Truncate Table back to empty status (from https://www.postgresql.org/docs/8.3/backup-dump.html)

Solution was to create separate DB for test, and TRUNCATE summoners table after test is done

**Comment by HelloFive** [comment]
Closing as PR has been merged
